### ISSUE TITLE
Z-order vs Hilbert

### ISSUE THREAD

**Issue by bdon** [protomaps/tippecanoe#16]
> -ah or --hilbert: Put features in Hilbert Curve order instead of the usual Z-Order. This improves the odds that spatially adjacent features will be sequentially adjacent, and should improve density calculations and spatial coalescing. It should be the default eventually.

@e-n-f do you have details around what the design tradeoffs were into defaulting to Hilbert vs Z-order in the future? like: 20% better locality at the expense of 10% more computation for encoding/decoding?

Related: https://github.com/protomaps/PMTiles/issues/67

**Comment by e-n-f** [comment]
@bdon It's terrible, but the only tradeoff I was really concerned about was that if I made `--hilbert` the default, all the test outputs would change and I would have to reeevaluate whether they all still made sense. I think any actual difference in running time is basically lost in the noise, and I should have just made it all Hilbert, all the time.

**Comment by bdon** [comment]
OK, I was curious if any experimental results were similar to what I got on a basemap (non-overlay) dataset here: https://github.com/protomaps/PMTiles/issues/67
