### ISSUE TITLE
Feature request: FlatGeobuf input

### ISSUE THREAD

**Issue by bdon** [protomaps/tippecanoe#2]
https://github.com/flatgeobuf/flatgeobuf is an alternative to both Geobuf and GeoJSON.

Advantage over Geobuf:
* supported directly by GDAL 3.1+
* less work (no deserialization step)

Advantage over GeoJSON:
* less work, possibly faster, but may not ultimately be a bottleneck

Other advantages:
* Can read an indexed FlatGeobuf to only grab a subset of data, but this would need an API.

Tippecanoe should be able to read a stream of flatgeobuf either from disk or from a pipe. It should support schema less (per-feature) input to have parity with geojson/geobuf. Possibly deprecate geobuf input to simplify overall.

**Comment by jjhembd** [comment]
I think deprecating geobuf makes sense. It doesn't seem to work for larger files--at least on my machine, json2geobuf runs out of memory with a 4.5 GB input. 

Based on [a comment from the developer](https://github.com/mapbox/geobuf/issues/103#issuecomment-450938700), memory issues may be inevitable with geobuf.

**Comment by bdon** [comment]
Relevant issue re: FlatGeobuf here: https://github.com/flatgeobuf/flatgeobuf/issues/125

**Comment by bdon** [comment]
In order to keep parity with the "GeoJSON Extension" described here: https://github.com/protomaps/tippecanoe#geojson-extension we need to think of a different strategy, since FlatGeobuf does not support arbitrary extensions like Geobuf does. The readme describes a way of modifying a ndjson by moving the relevant properties from the normal GeoJSON feature `properties`. For the FlatGeobuf case we can define a set of prefixes for properties like `tippecanoe:maxzoom` instead of needing the extension.

**Comment by bjornharrtell** [comment]
@bdon nice to see this initiative! Does this still mean a Go (reference?) implementation is needed?

**Comment by bdon** [comment]
@bjornharrtell while I'd like it for my other projects, a Go implementation isn't needed for tippecanoe - I have vendored in the C++ headers here https://github.com/protomaps/tippecanoe/tree/flatgeobuf which should be all that is necessary.

**Comment by bdon** [comment]
Checklist:

- [ ] support for streaming via stdin, should detect GeoJsonSeq vs FGB magic number
- [ ] support for `tippecanoe` GeoJSON/Geobuf extensions via namespaced properties `tippecanoe:maxzoom` etc
- [ ] support for embedding FGB primary keys (sequence numbers) in output tiles
- [ ] decompress gzip or zstd (#4) fgbs

**Comment by bdon** [comment]
- [ ] verify all columns are translated correctly to MVT, other than binary (not representable)

**Comment by bdon** [comment]
Migrated to https://github.com/felt/tippecanoe/issues/21
